### ISSUE TITLE
Integration into castle

### ISSUE THREAD

**Issue by generik0** [EurofficeGroup/windsor-service-provider#1]
Hi @ltines 
I can do some work with you on Friday if you like.  How can I help? What are your plans like?
You can contact me on rsr@gait.dk if you want to arrange a skype chat or something?

What are your thoughts.? If you want the commits in Castle, you will need to do the fork/transfer. I can help with some testing if you like :-)
How goes with the MS tests?

**Comment by ltines** [comment]
Hi @generik0,

already opened PR into the Castle project

**Comment by generik0** [comment]
Perfect!
